create database blood_bank_dhruv;

use blood_bank_dhruv;               

CREATE TABLE DOCTOR              
( D_ID CHAR(5) PRIMARY KEY,
  D_Name VARCHAR(20) NOT NULL ,
  D_DOB DATE NOT NULL ,
  D_BG VARCHAR(3) NOT NULL ,
  D_Gender CHAR(1),
  D_Ph_No VARCHAR(10),
  D_Address VARCHAR(30),
  D_Degree VARCHAR(15),
  D_Hospital VARCHAR(15),
  D_Doc_Certi_No VARCHAR(10) UNIQUE NOT NULL
  );

CREATE TABLE DONOR
( Dn_ID VARCHAR(5)PRIMARY KEY,
  Dn_Name VARCHAR(20) NOT NULL ,
  Dn_DOB DATE NOT NULL ,
  Dn_BG VARCHAR(3) NOT NULL ,
  Dn_Gender CHAR(1),
  Dn_Ph_No VARCHAR(10),
  Dn_Address VARCHAR(30),
  Dn_Donatable CHAR(1) NOT NULL,
  Dn_Cert_Doc CHAR(5) NOT NULL REFERENCES DOCTOR(D_ID)
);

CREATE TABLE RECIPIENT
( R_ID VARCHAR(5)PRIMARY KEY,
  R_Name VARCHAR(20) NOT NULL ,
  R_DOB DATE NOT NULL ,
  R_BG VARCHAR(3) NOT NULL ,
  R_Gender CHAR(1),
  R_Ph_No VARCHAR(10),
  R_Address VARCHAR(30)
);

CREATE TABLE BLOOD_BAG
( B_Bag_No VARCHAR(5)PRIMARY KEY,
  B_Dn_ID VARCHAR(5) NOT NULL REFERENCES DONOR(Dn_ID),
  B_Dn_Date DATE NOT NULL,
  B_Exp_Date DATE,
  B_Amount VARCHAR(10),
  B_Avail CHAR(1) NOT NULL,
  B_RecFlag CHAR(1) NOT NULL,
  B_R_ID VARCHAR(5) REFERENCES RECIPIENT(R_ID),
  B_R_Date DATE
  );